name: Update Leaderboard

on:
  push:
    branches:
      - main
    paths:
      - 'solutions/**'
  schedule:
    - cron: '*/10 * * * *'  # Run every 10 minutes

jobs:
  update-leaderboard:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Debug Directory Structure
      run: ls -R

    - name: Run Update Leaderboard Script
      run: python scripts/update_leaderboard.py

    - name: Commit and Push Leaderboard
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add LEADERBOARD.md progress.json
        git commit -m "Update leaderboard [auto]" || echo "No changes to commit"
        git push
